### PR TITLE
Add notification page. #63

### PR DESCRIPTION
**Pull request by Adrian-St**
Add overview page for notifications. The notifications page is not yet accessible via the header, for that is another user story in another issue. To look at the new functionality

 - be logged in
 - go to `/notifications/new` and create a notification
 - look at `/notifications` to see all notifications for you

notifications_page

### CODE REVIEW

**Comment by arne-z** [comment]
If possible, you should display an empty list or a text saying "You don't have any notifications at the moment" when visiting the page while I have no notifications. You should avoid displaying pages with only a headline and no content as it looks very wierd to the user.

**Comment by hkohlsaat** [comment]
@arne-z please have a look on the explanatory text which is displayed on the notification page, if no notifications are there to be displayed, and let us know, so we can assign reviewers. Thx

**Comment by hkohlsaat** [comment]
# Next steps
- [ ] let arne look over it
- [ ] run rubocop autofix
- [ ] assign reviewers
- [ ] merge

**Comment by arne-z** [comment]
I've looked over it and it is fine so far.

**Pull request merged**
