### PR TITLE
add "Prefab seed" Test users for different roles, usable in OpenID Testmode

### PR DESCRIPTION
**Pull request by skydivin4ng3l**
add "Prefab" Test users for different roles, usable in OpenID Testmode just comment in the user with the role you which to login with when clicking login with OAuth on Local Dev Server.

### CODE REVIEW

**Comment by skydivin4ng3l** [comment]
@jakobmache what am i doing wrong? does not work as intended?

**Comment by skydivin4ng3l** [comment]
@BjoernDaase asked that this PR should be completed, but I can't do it by my own. Can no longer drop DB on local maschine for example and I don't know what I am doing wrong, I thought that this is how @jakobmache explained it.

**Comment by skydivin4ng3l** [comment]
supposed to fix #306 or would should we do this?

**Comment by krichly** [comment]
Not needed!

**Comment by BjoernDaase** [comment]
I also think this PR can be closed because we have the Development LogIn in development mode, where you can choose whether you wan't to be an admin, employee or regular user.

**Comment by chrisma** [comment]
The only changes in this PR are currently 5 lines of comments to ` db/seeds.rb`.
The goal of this PR seems addressed by other PRs, i.e. https://github.com/hpi-swt2/vm-portal/pull/439, so closing for now.

**Pull request closed without merging**
