### PR TITLE
430/Refactor buttons

### LINKED ISSUE #430: Refactor buttons on editing request page
**Description**

The section on the bottom of the page should be refactored corresponding to the screenshot. 
img_3325

### PR DESCRIPTION
**Pull request by BjoernDaase**
Fixes #430 
Branched from #420, because I need the new `link_to` instead of `button_to`. Please merge #420 first!

### CODE REVIEW

**Comment by BjoernDaase** [comment]
@BraunTom @MrModder Does anybody of you have an idea how we could swap the positions "Accept" and the "Reject" buttons?

**Comment by BjoernDaase** [comment]
@krichly How important is the ordering of the "Accept" and "Reject" buttons?

**Comment by chrisma** [comment]
> @BraunTom @MrModder Does anybody of you have an idea how we could swap the positions of the "Accept" and the "Reject" button?

Bootstrap provides CSS classes that allow this, i.e. regarding [floats](https://getbootstrap.com/docs/4.0/utilities/float/) and [spacing](https://getbootstrap.com/docs/4.0/utilities/spacing/).
See my commit in this branch: https://github.com/hpi-swt2/vm-portal/pull/440/commits/66e24fc5edd277b6639c7c3f30b52d9359730ef6

**Comment by BjoernDaase** [comment]
> @BjoernDaase
> 
> > @BraunTom @MrModder Does anybody of you have an idea how we could swap the positions of the "Accept" and the "Reject" button?
> 
> Bootstrap provides CSS classes that allow this, i.e. regarding [floats](https://getbootstrap.com/docs/4.0/utilities/float/) and [spacing](https://getbootstrap.com/docs/4.0/utilities/spacing/).
> See my commit in this branch: [66e24fc](https://github.com/hpi-swt2/vm-portal/commit/66e24fc5edd277b6639c7c3f30b52d9359730ef6)
> 
> image

Nice, I didn't know that!

**Comment by chrisma** [comment]
@BjoernDaase @BraunTom @MrModder 
Anyone willingto be a hero and resolve the merge conflicts of this PR? :1st_place_medal:

**Comment by BjoernDaase** [comment]
> @BjoernDaase @BraunTom @MrModder
> Anyone willing to be a hero and resolve the merge conflicts of this PR and merge it?

I'll look into it.

**Comment by BjoernDaase** [comment]
Ok, merged it. Could somebody please doublecheck that it I didn't brick anything?

**Pull request merged**
