### PR TITLE
Sprint 1

### PR DESCRIPTION
**Pull request by MkuuWaUjinga**
This PR contains all the user stories that were completed in the last sprint.
- There is a VM and a Server page + details page for each one of them.
- ...

### CODE REVIEW

**Comment by chrisma** [comment]
The Travis CI build of this PR seems stuck
image
The solutions mentioned in the [Travis community](https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154) do not seem to apply here though, as we are already using the new GitHub Check Runs API, see [here](https://github.com/hpi-swt2/vm-portal/settings/branch_protection_rules/2823552).

**Comment by chrisma** [comment]
Is it intended that this PR merges from the `sprint-1` branch to `master` and does not involve the `dev` branch?

**Comment by MkuuWaUjinga** [comment]
> Is it intended that this PR merges from the `sprint-1` branch to `master` and does not involve the `dev` branch?

Yes, we cherry-picked the last commit on `dev` for Sprint 1 and branched from there in order to avoid that new features merged into `dev` during this Sprint are added to the PR.

**Comment by marcfreiheit** [comment]
Closed due to Travis issues. New pull request: #139

**Pull request closed without merging**
