### PR TITLE
452/Update design of config edit page

### LINKED ISSUE #446: Make mac address copy link great again
https://hart-dev.epic-hpi.de/vms/configs/show

### LINKED ISSUE #452: Refactoring VMs config page
- [x] Relocating operating system 
- [x] Update text elements (see picture) 

Related Issues: #449, #446 

bildschirmfoto 2019-03-07 um 12 53 22

### PR DESCRIPTION
**Pull request by BjoernDaase**
Fixes #452, also closes #446

@BraunTom Could you help me with the JS part here?

### CODE REVIEW

**Comment by chrisma** [comment]
Could we please use the gem bundled version of the employed JS library? https://github.com/sadiqmmm/clipboard-rails

It also includes some nice JS for including the "copy" button, which takes advantage of HTML data attributes for configuration, so that the amount of custom JS is minimal:

```
<!-- Target -->
<textarea id="bar">Mussum ipsum cacilds...</textarea>

<!-- Trigger -->
<button class="clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#bar">
    Copy to clipboard
</button>
```

**Comment by BjoernDaase** [comment]
@chrisma I'm sorry, but I don't get this working. Having 
```<button class="clipboard-btn" data-clipboard-action="copy" data-clipboard-target="#bar">
    Copy to clipboard
</button>```
in my code always submits the form as well.

**Comment by chrisma** [comment]
@BjoernDaase Thanks for the fast reply!

> in my code always submits the form as well.

If you've already investigated this and have some code, could you share your code (maybe in a separate branch/PR), so we can debug?

**Comment by BjoernDaase** [comment]
@chrisma Voila https://github.com/hpi-swt2/vm-portal/tree/debug/452

**Comment by chrisma** [comment]
@BjoernDaase 
> Voila https://github.com/hpi-swt2/vm-portal/tree/debug/452
Thanks. I have pushed two commits to that branch which fix the issues.

> in my code always submits the form as well.
See my comment on the other branch https://github.com/hpi-swt2/vm-portal/pull/465#issuecomment-471972519

**Comment by BjoernDaase** [comment]
@chrisma Looks good now. Can we merge?

**Pull request merged**
