### PR TITLE
262/filter search all users page

### LINKED ISSUE #262: filter and search all-users page
[//]: # (Lines starting with [//]: are considered to be comments. You do not have to delete those lines, they are not rendered upon release.)

**User Story**

[//]: # (Be descriptive about your user story. Who requests a feature and what's his intent?)

As an admin, I want to be able to filter and search the all-users page, to find what I'm looking for faster.
For this I need a search-box that lets me search the names of users as well as a filter for the different roles.

**Acceptance Criteria:**

- [x] There is a search box with which I can search for the name of a user
- [x] There is an option for filtering users by roles

[//]: # (Please don't forget to add the priority and complexity label to this issue.)

### PR DESCRIPTION
**Pull request by BjoernDaase**
Fixes #262, does lots of refactoring

### CODE REVIEW

**Comment by chrisma** [comment]
I would prefer if all sorting and filtering were to happen on the client side in the front end.
Ideally, this would involve no custom JavaScript code that needs to be maintained or any hidden fields in forms. A normal HTML table with all data should be constructed by RoR and the table should then be processed by JavaScript to add additional functionality. All configuration options for the table should be passed as [`data`](https://www.w3schools.com/tags/att_global_data.asp) attributes.

**Comment by MrModder** [comment]
We are currently using html elements as parts of our tables, e.g. for the user role changing, or the status indication of the vms. For those elements, custom, hidden data must be used for searching/ordering. Does datatables support this?
Please also be aware that changing all our tables to work properly with datatables will take time. We have a solution that is working for our current use case. Are you certain you want us to migrate to datatables now? Otherwise I suggest merging this PR and opening a separate issue for the conversion to datatables. In this case I would also add a comment to the filter_tables javascript function as a warning to convert to datatables before anyone does any further work on it.

**Comment by chrisma** [comment]
> For those elements, custom, hidden data must be used for searching/ordering. Does datatables support this?
Good points. I assume so, this would be part of implementation efforts. This explanation could be added as  comments to `app/assets/javascripts/sort_table.js` and `app/assets/javascripts/filter_table.js` in order to explain the rational for these extra pieces of JS.

> Otherwise I suggest merging this PR and opening a separate issue for the conversion to datatables.
Agreed.

**Comment by BjoernDaase** [comment]
Alright, so we can merge @chrisma?

**Comment by chrisma** [comment]
Is the codefactor issue relevant?
https://www.codefactor.io/repository/github/hpi-swt2/vm-portal/pull/418

**Comment by BjoernDaase** [comment]
> Is the codefactor issue relevant?
> https://www.codefactor.io/repository/github/hpi-swt2/vm-portal/pull/418

No, it's just CodeFactors fault, which doesn't know that the function is called because it happens implicitly.

**Comment by chrisma** [comment]
> No, it's just CodeFactors fault, which doesn't know that the function is called because it happens implicitly.
Alright, I've ignored the issue on Codefactor

**Comment by BjoernDaase** [comment]
> This looks alright, even though I would appreciate some comments on the JavaScript code, detailing why it is needed.

You mean why we use a custom filtering?

**Comment by chrisma** [comment]
> You mean why we use a custom filtering?

Yes, why the `//= require sort_table` is not enough.

**Comment by MrModder** [comment]
> You mean why we use a custom filtering?
> 
> Yes, why the //= require sort_table is not enough.

Do you mean why we need code in the _footer.erb?
Or are we talking about the custom filtering code (filter_table.js) or the sorting code (sort_table.js)?

**Comment by chrisma** [comment]
> Or are we talking about the custom filtering code (filter_table.js) or the sorting code (sort_table.js)?

Some code comments for future maintainers in `app/assets/javascripts/filter_table.js` and `app/assets/javascripts/sort_table.js` would be appreciated. JS code traditionally does not age well.

**Pull request merged**
